name: vape_zone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flexify: ^2.1.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  liquid_swipe: ^3.1.0
  lottie: ^3.1.2
  persistent_shopping_cart: ^0.0.7
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/Smoke Anim.json
    - assets/images/accessories.jpeg
    - assets/images/coils.jpeg
    - assets/images/disposable.jpeg
    - assets/images/juices.jpeg
    - assets/images/pods.jpeg
    - assets/images/vapes.jpeg
    - assets/animations/Animation - 1725129474665.json
    - assets/images/used vape.jpeg
    - assets/images/offers.jpeg
