// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfebjIoOXtbNZKafXj8NQ7odAuKWWzwnc',
    appId: '1:357117623376:web:130091789d5552d372a555',
    messagingSenderId: '357117623376',
    projectId: 'vape-zone-7cdca',
    authDomain: 'vape-zone-7cdca.firebaseapp.com',
    storageBucket: 'vape-zone-7cdca.appspot.com',
    measurementId: 'G-7Y0ZJX853H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXWyJGkhc-OJNaybHX_qs5JIOv_jrfgto',
    appId: '1:357117623376:android:6e519609fe2c50b072a555',
    messagingSenderId: '357117623376',
    projectId: 'vape-zone-7cdca',
    storageBucket: 'vape-zone-7cdca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfK9duv88e1ezNYFxKpQgNiXblrs0dXho',
    appId: '1:357117623376:ios:0c56faf5f114bd5772a555',
    messagingSenderId: '357117623376',
    projectId: 'vape-zone-7cdca',
    storageBucket: 'vape-zone-7cdca.appspot.com',
    iosBundleId: 'com.example.vapeZone',
  );
}
